version: '3'
services:
  go:
    build: ./goserver
    container_name: go-server
    restart: on-failure
    volumes:
      - ./goserver:/goserver
    command: go run main.go
    ports:
      - "80:80"